[package]
name = "krunvm"
version = "0.1.0"
authors = ["Sergio Lopez <slp@redhat.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.3"
confy = "0.4.0"
libc = "0.2.82"
serde = "1.0.120"
serde_derive = "1.0.120"
text_io = "0.1.8"